server:
  port: 9093

spring:
  application:
    name: FeesService

  

  datasource:
    url: jdbc:mysql://localhost:3306/feeService
    username: root
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
