server:
  port: 9092

spring:
  application:
    name: StudentService

  datasource:
    url: jdbc:mysql://localhost:3306/studentsdb
    username: root
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

 

feign:
  client:
    config:
      default:
        loggerLevel: full
  hystrix:
    enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
