spring:
  application:
    name: TeacherService

  datasource:
    url: jdbc:mysql://localhost:3306/teacherdatabase
    username: root
    password: root12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
      format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mySuperSecretKeyWhichIsLongEnoughForHS512
  expiration: 3600000   # 1 hour in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
