spring:
  application:
    name: Teacher
boot:
  admin:
    client:
       url: http://localhost:1111/

     
        
jpa:
        hibernate:
          ddl-auto: update  # Options: none, validate, update, create, create-drop
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
          hibernate:
            format_sql: true

management:
      endpoints:
        web:
          exposure:
            include:
              - '*'


server:
  port: 8000

datasource:
 url: jdbc:mysql://localhost:3306/teacherdatabase
 username: root
 password: root12345
 driver-class-name: com.mysql.cj.jdbc.Driver



eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
