spring:
  application:
    name: Teacher

server:
  port: 8000

datasource:
 url: jdbc:mysql://localhost:3306/teacherdatabase
 username: root
 password: root12345
jpa:
 hibernate:
     ddl-auto: update
 show-sql: true

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
